export const logos = [
  // Inner Orbit (orbitIndex: 0)
  {
    id: 1,
    name: "Dexe Protocol",
    imageSrc: "/assets/partners/dexe-black.png",
    orbitIndex: 0,
  },
  {
    id: 2,
    name: "Solid Proof",
    imageSrc: "/assets/partners/solid-proof-black.png",
    orbitIndex: 0,
  },
  {
    id: 3,
    name: "Paal AI",
    imageSrc: "/assets/partners/paal-ai.png",
    orbitIndex: 0,
  },
  {
    id: 4,
    name: "Social Data Analytics",
    imageSrc: "/assets/partners/social-data-analytics.png",
    orbitIndex: 0,
  },
  {
    id: 5,
    name: "Open Gate",
    imageSrc: "/assets/partners/opengate.png",
    orbitIndex: 0,
  },
  {
    id: 6,
    name: "Filescriptions",
    imageSrc: "/assets/partners/filscriptions.png",
    orbitIndex: 0,
  },
  {
    id: 7,
    name: "Way Network",
    imageSrc: "/assets/partners/way.png",
    orbitIndex: 0,
  },

  // Outer Orbit (orbitIndex: 1)
  {
    id: 8,
    name: "Metakraft AI",
    imageSrc: "/assets/partners/metakraft-ai.png",
    orbitIndex: 0,
  },
  {
    id: 9,
    name: "GemX Crypto",
    imageSrc: "/assets/partners/gemx-crypto.png",
    orbitIndex: 0,
  },
  {
    id: 10,
    name: "Satochain",
    imageSrc: "/assets/partners/sato-chain.png",
    orbitIndex: 0,
  },
  {
    id: 11,
    name: "Hambit",
    imageSrc: "/assets/partners/hambit.png",
    orbitIndex: 0,
  },
  {
    id: 12,
    name: "Sky Hause",
    imageSrc: "/assets/partners/sky-hause-logo.jpg",
    orbitIndex: 0,
  },
  {
    id: 13,
    name: "X-Alpha",
    imageSrc: "/assets/partners/x-alpha.png",
    orbitIndex: 0,
  },
  {
    id: 14,
    name: "GintonicAI",
    imageSrc: "/assets/partners/gintonic-ai-logo.jpg",
    orbitIndex: 0,
  },
  {
    id: 15,
    name: "OpenName",
    imageSrc: "/assets/partners/openname-black.png",
    orbitIndex: 0,
  },
  {
    id: 16,
    name: "Cluster Protocol",
    imageSrc: "/assets/partners/cluster-protocol-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 17,
    name: "ReflectionAI",
    imageSrc: "/assets/partners/reflection-ai-logo.png",
    orbitIndex: 1,
  },
  {
    id: 18,
    name: "Ottochain",
    imageSrc: "/assets/partners/ottochain-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 19,
    name: "Haya Finance",
    imageSrc: "/assets/partners/haya-logo.png",
    orbitIndex: 1,
  },
  {
    id: 20,
    name: "Thravos",
    imageSrc: "/assets/partners/thravos-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 21,
    name: "VPS AI",
    imageSrc: "/assets/partners/vpsai-logo.png",
    orbitIndex: 1,
  },
  {
    id: 22,
    name: "Agent Layer",
    imageSrc: "/assets/partners/agent-layer-logo.png",
    orbitIndex: 1,
  },
  {
    id: 23,
    name: "Synbo Protocol",
    imageSrc: "/assets/partners/ottochain-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 24,
    name: "SynonAI",
    imageSrc: "/assets/partners/synon-ai.jpg",
    orbitIndex: 1,
  },
  {
    id: 25,
    name: "Tokenwars",
    imageSrc: "/assets/partners/tokenwars-logo.png",
    orbitIndex: 1,
  },
  {
    id: 26,
    name: "Chronicles Of Warcraft",
    imageSrc: "/assets/partners/chronicles-of-warcraft-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 27,
    name: "Youflix",
    imageSrc: "/assets/partners/youflix-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 28,
    name: "BuddyAI",
    imageSrc: "/assets/partners/buddy-ai-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 29,
    name: "SuperString AI",
    imageSrc: "/assets/partners/superstring-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 30,
    name: "Ring AI | $RING",
    imageSrc: "/assets/partners/ringai-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 31,
    name: "DSCLAB",
    imageSrc: "/assets/partners/dsc-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 32,
    name: "ZERO Labs",
    imageSrc: "/assets/partners/zero-labs-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 33,
    name: "Zkgrok",
    imageSrc: "/assets/partners/zkgrok-black.png",
    orbitIndex: 1,
  },
  {
    id: 34,
    name: "XeroAI",
    imageSrc: "/assets/partners/xero-ai-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 35,
    name: "Collably Network",
    imageSrc: "/assets/partners/collably-network-logo.png",
    orbitIndex: 1,
  },
  {
    id: 36,
    name: "FD CAPITAL",
    imageSrc: "/assets/partners/fd-capital-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 37,
    name: "Luna PR",
    imageSrc: "/assets/partners/luna-pr-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 38,
    name: "Notif AI",
    imageSrc: "/assets/partners/$notif-ai.png",
    orbitIndex: 1,
  },
  {
    id: 39,
    name: "Bitgert - $BRISE",
    imageSrc: "/assets/partners/bitgert-logo.png",
    orbitIndex: 1,
  },
  {
    id: 40,
    name: "Voice AI",
    imageSrc: "/assets/partners/voice-ai.jpg",
    orbitIndex: 1,
  },
  {
    id: 41,
    name: "XallyAI",
    imageSrc: "/assets/partners/xally-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 42,
    name: "Kredly",
    imageSrc: "/assets/partners/kredly-logo.svg",
    orbitIndex: 1,
  },
  {
    id: 43,
    name: "Hemera Trading AI",
    imageSrc: "/assets/partners/hemera-trading-ai.jpg",
    orbitIndex: 1,
  },
  {
    id: 44,
    name: "Chainpal",
    imageSrc: "/assets/partners/chainpal-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 45,
    name: "IBIT",
    imageSrc: "/assets/partners/ibit-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 46,
    name: "DMAIL.AI",
    imageSrc: "/assets/partners/dmail-ai-logo.jpg",
    orbitIndex: 1,
  },
  {
    id: 47,
    name: "Masterblox",
    imageSrc: "/assets/partners/masterblox.png",
    orbitIndex: 1,
  },
  // {
  //   id: 48,
  //   name: "Aethir",
  //   imageSrc: "/assets/partners/aethir.svg",
  //   orbitIndex: 1,
  // },
];
